import test from 'node:test';
import assert from 'node:assert/strict';
import {createConversationStore, PREFIX} from '../src/conversations.js';
function local(){const data=new Map();return {get length(){return data.size},key:i=>[...data.keys()][i],getItem:k=>data.get(k)||null,setItem:(k,v)=>data.set(k,v),removeItem:k=>data.delete(k)};}
const conversation=(id,text)=>({id,title:text,updatedAt:1,messages:[{kind:'question',text},{kind:'answer',id:'structures.tension',mode:'shortAnswer'}]});
test('conserva preguntes i converses després de reobrir, i elimina només la seleccionada',()=>{const disk=local(),first=createConversationStore(disk);first.save(conversation('a','Què és tracció?'));first.save(conversation('b','Compressió?'));const reopened=createConversationStore(disk);assert.equal(reopened.list().length,2);assert.equal(reopened.get('a').messages[0].text,'Què és tracció?');reopened.remove('a');assert.equal(createConversationStore(disk).list().length,1);assert.ok(reopened.get('b'));});
test('les pestanyes llegeixen els canvis i no sobreescriuen altres converses',()=>{const disk=local(),a=createConversationStore(disk),b=createConversationStore(disk);a.save(conversation('a','A'));b.save(conversation('b','B'));const c=b.get('a');c.messages.push({kind:'unknown'});b.save(c);assert.equal(a.get('a').messages.length,3);assert.equal(a.list().length,2);});
test('quota exhaurida conserva els canvis en memòria i avisa',()=>{const disk=local(),warnings=[],store=createConversationStore(disk,m=>warnings.push(m));store.save(conversation('a','Original'));disk.setItem=()=>{throw Error('QuotaExceededError')};const c=store.get('a');c.messages.push({kind:'unknown'});assert.equal(store.save(c),false);assert.equal(store.get('a').messages.length,3);assert.ok(warnings.length);});
test('dades malmeses no amaguen converses vàlides',()=>{const disk=local(),store=createConversationStore(disk);disk.setItem(PREFIX+'bad','not json');store.save(conversation('ok','Vàlida'));assert.equal(store.list().length,1);});
