import test from 'node:test';
import assert from 'node:assert/strict';
import {createEngine} from '../src/engine/search-engine.js';
import {normalize} from '../src/engine/normalizer.js';
import {loadKnowledge,validate} from '../scripts/validate.mjs';
const modules=await loadKnowledge(),engine=createEngine(modules);
const groups={triangulation:['per què una estructura triangulada és resistent?','perque una estructura triangulada es resistent','pq les estructures triangulades aguanten?','pq els triangles aguanten mes?','perquè els ponts tenen triangles?','perquè les torres estan fetes amb triangles?','estructura triangulda resistent','els triangles fan que sigui més fort?'],tension:['que es la traccio?','què és tracció?','que vol dir estirar una barra?','tracio'],compression:['que és compressió?','què passa si aixafem una columna?','conpresio'],properties:['quina diferència hi ha entre estabilitat i rigidesa?'], 'shell-frame':['quina diferència hi ha entre estructura laminar i entramada?']};
for(const [id,queries] of Object.entries(groups))for(const q of queries)test(q,()=>{const r=engine.search(q);assert.equal(r.id,`structures.${id}`);assert.notEqual(r.status,'unknown');});
for(const q of ['qui és messi?','quina temperatura fa?','que és la llei d’ohm?','quant és 2+2?','','hola','em dic Anna i tinc dotze anys'])test('fora de temari: '+q,()=>assert.equal(engine.search(q).status,'unknown'));
test('ambigüitat: triangles millors',()=>assert.equal(engine.search('perquè els triangles són millors?').status,'clarify'));
test('el context no converteix una pregunta aliena en resposta',()=>assert.equal(engine.search('quina temperatura fa?',{context:'structures.tension'}).status,'unknown'));
test('pregunta llarga reconeix el concepte sense inventar',()=>{const r=engine.search('Hola, voldria saber si em pots explicar per què una estructura triangulada és resistent perquè no ho entenc');assert.equal(r.id,'structures.triangulation');assert.notEqual(r.status,'unknown');});
test('normalització prudent',()=>assert.equal(normalize(' PQ  tracció? '),'perque traccio'));
test('accents i plurals',()=>assert.equal(engine.search('bigues').id,'structures.beams'));
test('tots els títols recuperen el seu concepte',()=>{for(const e of engine.entries)assert.equal(engine.search(e.title).id,e.id,e.title);});
test('duplicats rebutjats',()=>{const m=structuredClone(modules);m[0].entries.push(m[0].entries[0]);assert.throws(()=>validate(m));});
test('relacions trencades rebutjades',()=>{const m=structuredClone(modules);m[0].entries[0].related.push('missing');assert.throws(()=>validate(m));});
test('respostes buides rebutjades',()=>{const m=structuredClone(modules);m[0].entries[0].easyAnswer='';assert.throws(()=>validate(m));});
test('mòdul desconegut rebutjat',()=>{const m=structuredClone(modules);m[0].entries[0].module='missing';assert.throws(()=>validate(m));});
test('enllaç malformat rebutjat',()=>{const m=structuredClone(modules);m[0].entries[0].page='javascript:alert(1)';assert.throws(()=>validate(m));});
test('tema nou incorporat només amb dades',()=>{const entry={...structuredClone(modules[0].entries[0]),id:'electricity.ohm',module:'electricity',title:'Llei d’Ohm',concepts:['ohm'],keywords:['ohm','tensio','intensitat'],expressions:['llei d ohm'],exampleQuestions:['què és la llei d’ohm?'],shortAnswer:'Relaciona tensió, intensitat i resistència.',related:[],page:'#electricity.ohm'};const data=[...modules,{id:'electricity',title:'Electricitat',synonyms:{},entries:[entry]}];validate(data);const next=createEngine(data);assert.equal(next.search('què és la llei d’ohm?').id,'electricity.ohm');assert.equal(next.search('què és la llei d’ohm?',{module:'structures'}).status,'unknown');});
